version: "3.7"

services:
  database:
    image: postgres
    container_name: just-a-simple-fin-app-database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=just-a-simple-fin-app
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: just-a-simple-fin-app-api
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
